---
# Collections required for Windows management and Vault integration
collections:
  - name: ansible.windows
    version: ">=2.0.0"
  - name: community.windows
    version: ">=2.0.0"
  - name: community.hashi_vault
    version: ">=6.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=8.0.0"

# Additional roles (if needed)
# roles:
#   - name: some.external.role
#     version: "1.0.0"
