---
# tasks file for vault_credential_rotation

- name: Get current service account credentials from Vault
  community.hashi_vault.vault_read:
    url: "{{ vault_url }}"
    auth_method: "{{ vault_auth_method }}"
    token: "{{ vault_token | default(omit) }}"
    path: "{{ vault_ldap_creds_path }}/{{ service_account_role }}"
  register: vault_creds
  delegate_to: localhost
  run_once: true

- name: Extract credentials from Vault response
  set_fact:
    current_username: "{{ vault_creds.data.data.username }}"
    current_password: "{{ vault_creds.data.data.password }}"
  delegate_to: localhost
  run_once: true

- name: Debug current credentials (username only)
  debug:
    msg: "Retrieved credentials for user: {{ current_username }}"
  when: debug_mode | default(false)

- name: Update Windows service account password
  ansible.windows.win_user:
    name: "{{ current_username }}"
    password: "{{ current_password }}"
    state: present
    password_never_expires: true
  register: password_update_result

- name: Update service logon credentials
  ansible.windows.win_service:
    name: "{{ item }}"
    username: "{{ service_domain }}\\{{ current_username }}"
    password: "{{ current_password }}"
  loop: "{{ target_services }}"
  register: service_update_result

- name: Restart services to apply new credentials
  ansible.windows.win_service:
    name: "{{ item }}"
    state: restarted
    start_mode: auto
  loop: "{{ target_services }}"
  when: restart_services | default(true)

- name: Verify service status after restart
  ansible.windows.win_service:
    name: "{{ item }}"
  loop: "{{ target_services }}"
  register: service_status

- name: Log credential rotation completion
  debug:
    msg: "Credential rotation completed for {{ current_username }} on {{ inventory_hostname }}"
