---
# Default variables for vault_credential_rotation role

# Vault configuration
vault_url: "{{ vault_server_url }}"
vault_auth_method: "token"
vault_ldap_creds_path: "ldap/creds"

# Service account configuration
service_account_role: "service-account-role"
service_domain: "{{ windows_domain }}"

# Services to update (override in inventory)
target_services: []

# Control flags
restart_services: true
debug_mode: false

# Notification settings
send_notifications: true
notification_webhook: ""
