---

- name: Get Current Service Status from Windows Hosts
  hosts: windows_servers
  gather_facts: false
  roles:
    - windows_service_status

- name: Get Service Account Credentials from Vault using EE
  hosts: localhost
  gather_facts: false
  vars:
    vault_addr: "{{ vault_url | default('https://vault.hashicorp.local:8200') }}"
    vault_ldap_mount: "{{ vault_ldap_mount_path | default('ldap') }}"
    vault_static_role: "{{ vault_static_role_name | default('svc_demo') }}"
  roles:
    - vault_credential_retrieval

- name: Update Service Credentials on Windows Hosts
  hosts: windows_servers
  gather_facts: false
  vars:
    # Pass credentials from Vault play to Windows hosts
    service_account: "{{ hostvars['localhost']['current_username'] }}"
    current_password: "{{ hostvars['localhost']['current_password'] }}"
    last_vault_rotation: "{{ hostvars['localhost']['last_vault_rotation'] }}"
    vault_static_role: "{{ hostvars['localhost']['vault_static_role'] }}"
  roles:
    - windows_service_credential_update
