---

- name: Get Current Service Status from Windows Hosts
  hosts: windows
  gather_facts: false
  roles:
    - windows_service_status

- name: Get Service Account Credentials from Vault using EE
  hosts: localhost
  gather_facts: false
  vars:
    vault_addr: "{{ vault_url | default('https://vault.hashicorp.local:8200') }}"
    vault_ldap_mount: "{{ vault_ldap_mount_path | default('ldap') }}"
    vault_static_role: "{{ vault_static_role_name | default('svc_demo') }}"
  roles:
    - vault_credential_retrieval

    - name: Extract current password from Vault response
      ansible.builtin.set_fact:
        current_username: "{{ vault_credentials.data.username }}"
        current_password: "{{ vault_credentials.data.password }}"
        last_vault_rotation: "{{ vault_credentials.data.last_vault_rotation | default('unknown') }}"

    - name: Display credential info (username only for security)
      ansible.builtin.debug:
        msg: 
          - "Retrieved current credentials for user: {{ current_username }}"
          - "Last Vault rotation: {{ last_vault_rotation }}"

# Play 2: Update Windows services with credentials (runs on Windows hosts)
- name: Update Windows Service Account Passwords
  hosts: windows_servers
  gather_facts: false
  vars:
    # SSH connection using proven working configuration
    ansible_connection: ssh
    ansible_shell_type: cmd
    ansible_port: 22
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    # Service configuration - can be overridden via extra variables
    service_account: "{{ vault_service_account | default('hashicorp.local\\svc-demo') }}"
    dependent_services: "{{ services_to_restart | default(['DemoHelloWorldService']) }}"
    
    # Get credentials from previous play
    current_username: "{{ hostvars['localhost']['current_username'] }}"
    current_password: "{{ hostvars['localhost']['current_password'] }}"
    last_vault_rotation: "{{ hostvars['localhost']['last_vault_rotation'] }}"

- name: Update Service Credentials on Windows Hosts
  hosts: windows
  gather_facts: false
  vars:
    # Pass credentials from Vault play to Windows hosts
    service_account: "{{ hostvars['localhost']['current_username'] }}"
    current_password: "{{ hostvars['localhost']['current_password'] }}"
    last_vault_rotation: "{{ hostvars['localhost']['last_vault_rotation'] }}"
    vault_static_role: "{{ hostvars['localhost']['vault_static_role'] }}"
  roles:
    - windows_service_credential_update
