---
- name: Rotate Windows Service Account Passwords
  hosts: windows_servers
  gather_facts: true
  vars:
    vault_lookup_retries: 3
    vault_lookup_delay: 5
  
  pre_tasks:
    - name: Ensure required variables are defined
      ansible.builtin.assert:
        that:
          - vault_url is defined
          - ldap_role_name is defined
          - service_accounts is defined
        fail_msg: "Required variables not defined. Check group_vars/windows_servers.yml"

    - name: Create log directory if it doesn't exist
      ansible.windows.win_file:
        path: "{{ log_directory }}"
        state: directory
      when: log_directory is defined

  tasks:
    - name: Get current credentials from Vault LDAP backend
      ansible.builtin.set_fact:
        vault_ldap_creds: "{{ lookup('community.hashi_vault.hashi_vault', 
          'ldap/creds/' + ldap_role_name, 
          url=vault_url, 
          token=vault_token) }}"
      retries: "{{ vault_lookup_retries }}"
      delay: "{{ vault_lookup_delay }}"
      register: vault_result
      until: vault_result is succeeded
      no_log: true

    - name: Extract credentials from Vault response
      ansible.builtin.set_fact:
        current_username: "{{ vault_ldap_creds.username }}"
        current_password: "{{ vault_ldap_creds.password }}"
      no_log: true

    - name: Display username (password hidden for security)
      ansible.builtin.debug:
        msg: "Retrieved credentials for user: {{ current_username }}"

    - name: Process each service account
      ansible.builtin.include_tasks: 
        file: tasks/update_service_account.yml
      vars:
        service_account_config: "{{ item }}"
        new_username: "{{ current_username }}"
        new_password: "{{ current_password }}"
      loop: "{{ service_accounts }}"
      loop_control:
        label: "{{ item.name }}"

  post_tasks:
    - name: Send notification if configured
      ansible.builtin.uri:
        url: "{{ notification_webhook }}"
        method: POST
        body_format: json
        body:
          message: "Service account password rotation completed on {{ inventory_hostname }}"
          hostname: "{{ inventory_hostname }}"
          timestamp: "{{ ansible_date_time.iso8601 }}"
          services_updated: "{{ service_accounts | map(attribute='name') | list }}"
      when: 
        - send_notifications | default(false)
        - notification_webhook is defined
      delegate_to: localhost

  handlers:
    - name: Log rotation completion
      ansible.windows.win_eventlog:
        log: Application
        source: "Ansible Service Management"
        event_id: 1001
        message: "Service account password rotation completed successfully"
        category: 1
        type: Information
