---
- name: Test Windows Connection via SSH
  hosts: windows_servers
  gather_facts: false
  vars:
    # SSH connection for Windows with explicit shell configuration
    ansible_connection: ssh
    ansible_shell_type: cmd
    ansible_port: 22
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
  tasks:
    - name: Test basic connectivity with simple command
      ansible.builtin.raw: echo hello
      register: hello_output
      changed_when: false
      
    - name: Display hello output
      ansible.builtin.debug:
        msg: "Output: {{ hello_output.stdout | default('no output') }}"
        
    - name: Test hostname command
      ansible.builtin.raw: hostname
      register: hostname_output
      changed_when: false
      
    - name: Display hostname
      ansible.builtin.debug:
        msg: "Hostname: {{ hostname_output.stdout | default('no output') }}"
