---
- name: Test Windows Connection via SSH
  hosts: windows_servers
  gather_facts: false
  vars:
    # SSH connection for Windows with OpenSSH
    ansible_connection: ssh
    ansible_shell_type: powershell
    ansible_ssh_shell_type: powershell
    ansible_port: 22
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
  tasks:
    - name: Test basic connectivity with raw command
      ansible.builtin.raw: echo "Hello World from {{ inventory_hostname }}"
      register: hello_output
      changed_when: false
      
    - name: Display hello output
      ansible.builtin.debug:
        msg: "{{ hello_output.stdout_lines }}"
        
    - name: Get current date and time
      ansible.builtin.raw: Get-Date
      register: datetime_output
      changed_when: false
      
    - name: Display current date/time
      ansible.builtin.debug:
        msg: "{{ datetime_output.stdout_lines }}"
